In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [7]:
import os

path = r"C:\Users\Nithin\OneDrive\Desktop\Projects\Spatial–Temporal Uber Fare Prediction Engine\Data\uber.csv"

print(os.path.exists(path))
print(os.path.isfile(path))

True
False

In [11]:
import os

folder = r"C:\Users\Nithin\OneDrive\Desktop\Projects\Spatial–Temporal Uber Fare Prediction Engine\Data"

print(os.listdir(folder))

['uber.csv', 'uber.csv.zip']

In [19]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Nithin\OneDrive\Desktop\Projects\Spatial–Temporal Uber Fare Prediction Engine\Data\uber.csv\uber.csv"
)

df.head()

,Unnamed: 0,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,24238194,2015-05-07 19:52:06.0000003,7.5,2015-05-07 19:52:06 UTC,-73.999817,40.738354,-73.999512,40.723217,1
1,27835199,2009-07-17 20:04:56.0000002,7.7,2009-07-17 20:04:56 UTC,-73.994355,40.728225,-73.994710,40.750325,1
2,44984355,2009-08-24 21:45:00.00000061,12.9,2009-08-24 21:45:00 UTC,-74.005043,40.740770,-73.962565,40.772647,1
3,25894730,2009-06-26 08:22:21.0000001,5.3,2009-06-26 08:22:21 UTC,-73.976124,40.790844,-73.965316,40.803349,3
4,17610152,2014-08-28 17:47:00.000000188,16.0,2014-08-28 17:47:00 UTC,-73.925023,40.744085,-73.973082,40.761247,5

In [21]:
import os

path = r"C:\Users\Nithin\OneDrive\Desktop\Projects\Spatial–Temporal Uber Fare Prediction Engine\Data\uber.csv\uber.csv"

print(os.path.exists(path))
print(os.path.isfile(path))

True
True

In [25]:
df.tail()

,Unnamed: 0,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
199995,42598914,2012-10-28 10:49:00.00000053,3.0,2012-10-28 10:49:00 UTC,-73.987042,40.739367,-73.986525,40.740297,1
199996,16382965,2014-03-14 01:09:00.0000008,7.5,2014-03-14 01:09:00 UTC,-73.984722,40.736837,-74.006672,40.739620,1
199997,27804658,2009-06-29 00:42:00.00000078,30.9,2009-06-29 00:42:00 UTC,-73.986017,40.756487,-73.858957,40.692588,2
199998,20259894,2015-05-20 14:56:25.0000004,14.5,2015-05-20 14:56:25 UTC,-73.997124,40.725452,-73.983215,40.695415,1
199999,11951496,2010-05-15 04:08:00.00000076,14.1,2010-05-15 04:08:00 UTC,-73.984395,40.720077,-73.985508,40.768793,1

In [27]:
df.shape

(200000, 9)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         200000 non-null  int64
 1   key                200000 non-null  object
 2   fare_amount        200000 non-null  float64
 3   pickup_datetime    200000 non-null  object
 4   pickup_longitude   200000 non-null  float64
 5   pickup_latitude    200000 non-null  float64
 6   dropoff_longitude  199999 non-null  float64
 7   dropoff_latitude   199999 non-null  float64
 8   passenger_count    200000 non-null  int64
dtypes: float64(5), int64(2), object(2)
memory usage: 13.7+ MB

In [31]:
df.describe()

,Unnamed: 0,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
count,2.000000e+05,200000.000000,200000.000000,200000.000000,199999.000000,199999.000000,200000.000000
mean,2.771250e+07,11.359955,-72.527638,39.935885,-72.525292,39.923890,1.684535
std,1.601382e+07,9.901776,11.437787,7.720539,13.117408,6.794829,1.385997
min,1.000000e+00,-52.000000,-1340.648410,-74.015515,-3356.666300,-881.985513,0.000000
25%,1.382535e+07,6.000000,-73.992065,40.734796,-73.991407,40.733823,1.000000
50%,2.774550e+07,8.500000,-73.981823,40.752592,-73.980093,40.753042,1.000000
75%,4.155530e+07,12.500000,-73.967154,40.767158,-73.963658,40.768001,2.000000
max,5.542357e+07,499.000000,57.418457,1644.421482,1153.572603,872.697628,208.000000

In [33]:
df.isnull().sum()

Unnamed: 0           0
key                  0
fare_amount          0
pickup_datetime      0
pickup_longitude     0
pickup_latitude      0
dropoff_longitude    1
dropoff_latitude     1
passenger_count      0
dtype: int64

In [35]:
df=df.dropna()

In [37]:
df=df.drop_duplicates()

In [39]:
df.drop("Unnamed: 0",axis=1,inplace=True)

In [41]:
df["pickup_datetime"]=pd.to_datetime(df["pickup_datetime"])

In [43]:
df["Year"]=df["pickup_datetime"].dt.year

df["Month"]=df["pickup_datetime"].dt.month

df["Day"]=df["pickup_datetime"].dt.day

df["Hour"]=df["pickup_datetime"].dt.hour

df["Minute"]=df["pickup_datetime"].dt.minute

df["Weekday"]=df["pickup_datetime"].dt.day_name()

In [45]:
df["Peak_Hour"]=np.where(
((df["Hour"]>=7)&(df["Hour"]<=10))|
((df["Hour"]>=17)&(df["Hour"]<=20)),
"Peak",
"Non Peak"
)

In [47]:
from math import radians,sin,cos,sqrt,asin

def haversine(lat1,lon1,lat2,lon2):

    lon1,lat1,lon2,lat2=map(
        radians,
        [lon1,lat1,lon2,lat2]
    )

    dlon=lon2-lon1
    dlat=lat2-lat1

    a=sin(dlat/2)**2+cos(lat1)*cos(lat2)*sin(dlon/2)**2

    c=2*asin(sqrt(a))

    r=6371

    return c*r

In [49]:
df["Distance_km"]=df.apply(
lambda x:
haversine(
x["pickup_latitude"],
x["pickup_longitude"],
x["dropoff_latitude"],
x["dropoff_longitude"]
),
axis=1
)

In [51]:
df["Distance_Category"]=pd.cut(
df["Distance_km"],
bins=[0,2,5,10,20,100],
labels=[
"Very Short",
"Short",
"Medium",
"Long",
"Very Long"
]
)

In [53]:
df["Fare_Category"]=pd.cut(
df["fare_amount"],
bins=[0,10,20,40,100,1000],
labels=[
"Low",
"Medium",
"High",
"Premium",
"Luxury"
]
)

In [55]:
df=df[df["fare_amount"]>0]

In [57]:
df=df[df["passenger_count"]>0]

In [59]:
df=df[
(df["pickup_latitude"]!=0)&
(df["pickup_longitude"]!=0)&
(df["dropoff_latitude"]!=0)&
(df["dropoff_longitude"]!=0)
]

In [61]:
Q1=df["fare_amount"].quantile(.25)

Q3=df["fare_amount"].quantile(.75)

IQR=Q3-Q1

lower=Q1-1.5*IQR

upper=Q3+1.5*IQR

df=df[
(df["fare_amount"]>=lower)&
(df["fare_amount"]<=upper)
]

In [65]:
import os

# Create folder if it doesn't already exist
os.makedirs(r"C:\Users\Nithin\OneDrive\Desktop\Projects\Spatial–Temporal Uber Fare Prediction Engine\Data\Cleaned data", exist_ok=True)

# Save cleaned dataset
df.to_csv(
    r"C:\Users\Nithin\OneDrive\Desktop\Projects\Spatial–Temporal Uber Fare Prediction Engine\Data\Cleaned data\cleaned_uber_data.csv",
    index=False
)

print("✅ Cleaned dataset saved successfully!")

✅ Cleaned dataset saved successfully!

In [67]:
import os

file_path = r"C:\Users\Nithin\OneDrive\Desktop\Projects\Spatial–Temporal Uber Fare Prediction Engine\Data\Cleaned data\cleaned_uber_data.csv"

print(os.path.exists(file_path))

True